name: CI

on: workflow_dispatch

jobs:

  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        pg-version: ['12', '13', '14', '15', '16']

    steps:
      - uses: actions/checkout@v1
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run pytest tests
        run: nix-shell --run "net-with-nginx net-with-pathod net-with-pg-${{ matrix.pg-version }} python -m pytest -vv"

      #- name: Check C files are formatted
        #run: nix-shell --run "net-check-format"
